### ISSUE TITLE
Gateways stall after 5 minutes when using reframe/delegated routing

### ISSUE THREAD

**Issue by ajnavarro** [ipfs/kubo#9445] opened 2022-12-02 10:11 UTC
### Version

```Text
v0.17.0
```

### Config

```json
"Routing": {
    "Methods": {
      "find-peers": {
        "RouterName": "DHTs"
      },
      "find-providers": {
        "RouterName": "ParallelHelper"
      },
      "get-ipns": {
        "RouterName": "DHTs"
      },
      "provide": {
        "RouterName": "DHTs"
      },
      "put-ipns": {
        "RouterName": "DHTs"
      }
    },
    "Routers": {
      "CidContact": {
        "Parameters": {
          "Endpoint": "https://cid.contact/reframe"
        },
        "Type": "reframe"
      },
      "ParallelHelper": {
        "Parameters": {
          "Routers": [
            {
              "IgnoreErrors": true,
              "RouterName": "CidContact",
              "Timeout": "3s"
            },
            {
              "IgnoreErrors": false,
              "RouterName": "DHTs",
              "Timeout": "5m"
            }
          ]
        },
        "Type": "parallel"
      },
      "DHTs": {
        "Parameters": {
          "Routers": [
            {
              "IgnoreErrors": false,
              "RouterName": "WanDHT",
              "Timeout": "5m"
            },
            {
              "IgnoreErrors": false,
              "RouterName": "LanDHT",
              "Timeout": "1m"
            }
          ]
        },
        "Type": "parallel"
      },
      "WanDHT": {
        "Parameters": {
          "AcceleratedDHTClient": true,
          "Mode": "auto",
          "PublicIPNetwork": true
        },
        "Type": "dht"
      },
      "LanDHT": {
        "Parameters": {
          "AcceleratedDHTClient": false,
          "Mode": "auto",
          "PublicIPNetwork": false
        },
        "Type": "dht"
      }
    },

    "Type": "custom"
  },
```

### Description

After ~5 minutes of having the following configuration, delegated routing stops sending find providers requests.

Might be a deadlock problem. A possible solution here: https://github.com/libp2p/go-libp2p-routing-helpers/pull/64

**Comment by BigLep** [comment] 2022-12-02 19:42
@ajnavarro @guseggert : I'm reopening because:
1. I don't see a regression test anywhere (looking at https://github.com/libp2p/go-libp2p-routing-helpers/pull/64 and https://github.com/ipfs/kubo/pull/9447 ).  How do we know this fixes the issue?  
2. Should we get https://github.com/libp2p/go-libp2p-routing-helpers/pull/63 merged as weel?

**Comment by guseggert** [comment] 2022-12-02 20:59
I added a test here: https://github.com/libp2p/go-libp2p-routing-helpers/pull/66

We should get the logging change merged too but I don't think it's necessary to unblock the gateway deployment

**Comment by guseggert** [comment] 2022-12-06 03:08
Fix has been merged & deployed, and I verified that the deadlock is no longer occurring.

**Closed by guseggert** 2022-12-06 03:08 UTC
Labels: kind/bug
