### ISSUE TITLE
Could not connect to the IPFS API from WebUI at http://0.0.0.0:5001/webui

### ISSUE THREAD

**Issue by gillbates** [ipfs/kubo#10515] opened 2024-09-15 09:41 UTC
### Checklist

- [X] This is a bug report, not a question. Ask questions on [discuss.ipfs.tech](https://discuss.ipfs.tech/c/help/13).
- [X] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my bug.
- [X] I am running the latest [kubo version](https://dist.ipfs.tech/#kubo) or have an issue updating.

### Installation method

built from source

### Description

using the original docker-compose.yml to start. it shows 

![CleanShot 2024-09-15 at 17 41 17@2x](https://github.com/user-attachments/assets/100950b7-2cb6-4b17-aadd-95f950deeb97)

do we need some other init process for this compose?

**Comment by lidel** [comment] 2024-09-17 22:26
@gillbates i was not able to reproduce

```console
$ > docker compose up
Attaching to kubo-ipfs-1
kubo-ipfs-1  | Changing user to ipfs
kubo-ipfs-1  | ipfs version 0.31.0-dev
kubo-ipfs-1  | generating ED25519 keypair...
kubo-ipfs-1  | done
kubo-ipfs-1  | peer identity: 12D3KooWFiiVnrcncbCmiVMbsrMyYG4CHPH75gUopvmMdnuSY7KJ
kubo-ipfs-1  | initializing IPFS node at /data/ipfs
kubo-ipfs-1  | Initializing daemon...
kubo-ipfs-1  | Kubo version: 0.31.0-dev-4236207
kubo-ipfs-1  | Repo version: 16
kubo-ipfs-1  | System version: amd64/linux
kubo-ipfs-1  | Golang version: go1.22.7
kubo-ipfs-1  | PeerID: 12D3KooWFiiVnrcncbCmiVMbsrMyYG4CHPH75gUopvmMdnuSY7KJ
kubo-ipfs-1  | Swarm listening on 127.0.0.1:4001 (TCP+UDP)
kubo-ipfs-1  | Swarm listening on [::1]:4001 (TCP+UDP)
kubo-ipfs-1  | Run 'ipfs id' to inspect announced and discovered multiaddrs of this node.
kubo-ipfs-1  | RPC API server listening on /ip4/0.0.0.0/tcp/5001
kubo-ipfs-1  | WebUI: http://0.0.0.0:5001/webui
kubo-ipfs-1  | Gateway server listening on /ip4/0.0.0.0/tcp/8080
kubo-ipfs-1  | Daemon is ready
```

Accessing WebUI via http://127.0.0.1:5001/webui works just fine:

> ![2024-09-18_00-25](https://github.com/user-attachments/assets/57597cb3-ee34-4c47-8d60-a730dfb65d10)

Do you mind providing reproduction steps of your problem?

**Comment by gillbates** [comment] 2024-09-18 10:03
> @gillbates i was not able to reproduce
> 
> ```
> $ > docker compose up
> Attaching to kubo-ipfs-1
> kubo-ipfs-1  | Changing user to ipfs
> kubo-ipfs-1  | ipfs version 0.31.0-dev
> kubo-ipfs-1  | generating ED25519 keypair...
> kubo-ipfs-1  | done
> kubo-ipfs-1  | peer identity: 12D3KooWFiiVnrcncbCmiVMbsrMyYG4CHPH75gUopvmMdnuSY7KJ
> kubo-ipfs-1  | initializing IPFS node at /data/ipfs
> kubo-ipfs-1  | Initializing daemon...
> kubo-ipfs-1  | Kubo version: 0.31.0-dev-4236207
> kubo-ipfs-1  | Repo version: 16
> kubo-ipfs-1  | System version: amd64/linux
> kubo-ipfs-1  | Golang version: go1.22.7
> kubo-ipfs-1  | PeerID: 12D3KooWFiiVnrcncbCmiVMbsrMyYG4CHPH75gUopvmMdnuSY7KJ
> kubo-ipfs-1  | Swarm listening on 127.0.0.1:4001 (TCP+UDP)
> kubo-ipfs-1  | Swarm listening on [::1]:4001 (TCP+UDP)
> kubo-ipfs-1  | Run 'ipfs id' to inspect announced and discovered multiaddrs of this node.
> kubo-ipfs-1  | RPC API server listening on /ip4/0.0.0.0/tcp/5001
> kubo-ipfs-1  | WebUI: http://0.0.0.0:5001/webui
> kubo-ipfs-1  | Gateway server listening on /ip4/0.0.0.0/tcp/8080
> kubo-ipfs-1  | Daemon is ready
> ```
> 
> Accessing WebUI via http://127.0.0.1:5001/webui works just fine:
> 
> > ![2024-09-18_00-25](https://private-user-images.githubusercontent.com/157609/368363187-57597cb3-ee34-4c47-8d60-a730dfb65d10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NTMxMDYsIm5iZiI6MTcyNjY1MjgwNiwicGF0aCI6Ii8xNTc2MDkvMzY4MzYzMTg3LTU3NTk3Y2IzLWVlMzQtNGM0Ny04ZDYwLWE3MzBkZmI2NWQxMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOFQwOTQ2NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMDViMjM5M2VkMzFhYWNjNDQzM2ZlMzZjM2Y1ZmVlMGQyODJkMDc3N2U1OGVkNGNiN2M5NDVhMTE5ODExMWQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._Yrc8Ma5_xrT_RJMsJRGw3aq5gCkNRbsFi0mhoHO38I)
> 
> I guess your setup looks different? Do you mind providing reproduction steps of your problem?

haha, I found the issue.
it works with the url: http://127.0.0.1:5001/
but it doesnot work with url: http://0.0.0.0:5001/

however the docker logs shows we should access the ipfs using http://0.0.0.0:5001/
maybe we should adjust some params in docker-compose? @lidel

**Comment by lidel** [comment] 2024-09-18 15:24
Ah, makes sense. 

This is a cosmetic issue with test printed on daemon start.

Docker image config has all listeners, including `Addresses.API` set to catch-all 0.0.0.0 (here,  `/ip4/0.0.0.0/tcp/5001`), and the WebUI URL should be normalized to useful local URL.

Will be fixed in https://github.com/ipfs/kubo/pull/10520, thank you for reporting this papercut.

**Closed** 2024-10-03 22:51 UTC
Labels: kind/bug, dif/easy
